Update and rename release.ubuntu to releaseresults

diff --git a/backend/release-scripts/releaseresults b/backend/release-scripts/releaseresults
--- a/backend/release-scripts/releaseresults
+++ b/backend/release-scripts/releaseresults
@@ -1,20 +1,20 @@
 #!/bin/bash
 
 # Copyright 2013 University of Michigan
-# 
+#
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
-# 
+#
 #     http://www.apache.org/licenses/LICENSE-2.0
-# 
+#
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-TIMEOUT=60
+TIMEOUT=5
 
 usage () {
 
@@ -51,6 +51,11 @@ if [[ "$ACTION" = "add" ]]; then
   fi
 
   zip -r /media/release_spool/results.zip "$@"
+  size=`ls -l /media/release_spool/results.zip | awk '{print $5}'`
+  if [ $size -ge 104857600 ]; then
+    echo "The size of the result released is " $size " bytes which is large. You may expect delay in getting the result back."
+    echo "If you want to start over your result release, please delete the results.zip under /media/release_spool"
+  fi
 
   exit 0
 
@@ -72,6 +77,13 @@ if [[ "$ACTION" = "done" ]]; then
     fi
    fi
 
+#  size=`ls -l /media/release_spool/results.zip | awk '{print $5}'`
+#  if [ $size -ge 104857600 ]; then
+#    echo "Result file size exceeds 100 MB! It cannot be released and will be delete! Please start over your release."
+#    rm -f /media/release_spool/results.zip
+#    exit 1
+#  fi
+
   echo "results.zip" >> /dev/ttyS0
 
   for time in $(seq 1 $TIMEOUT); do
@@ -81,18 +93,18 @@ if [[ "$ACTION" = "done" ]]; then
     sleep 1
   done
 
-  if [ ! -e /media/release_spool/done ]; then
-    echo "Error: Results release timed out.  Try again, and if problem"
-    echo "       persists, please contact an administrator for assistance." 
-    exit 3
-  fi
+#  if [ ! -e /media/release_spool/done ]; then
+#    echo "Error: Results release timed out.  Try again, and if problem"
+#    echo "       persists, please contact an administrator for assistance."
+#    exit 3
+#  fi
 
   rm -rf /media/release_spool/{done,results.zip}
 
+  echo "Your results are under review. We will get back to you in two business days by email."
   exit 0
 
 fi
 
 usage
 exit 1
-
